apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datapvc
  namespace: state
  labels:
    app: db
    type: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi