apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-pv
spec:
  capacity:
    storage: 3G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 172.31.3.217
