apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  labels:
    app: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/    # nfs server share directory
    server: 172.31.3.217  # nfs-server ip