apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata-pv
  labels: 
    app: datastore
spec:
  capacity:
    storage: 3G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 172.31.3.217
