apiVersion: v1
kind: Service
metadata:
  name: build-app-svc
  namespace: builds
spec:
  selector:
    type: infra
    app: infra_apps
# ports:
# - port: 80
#   targetPort: 80
  type: ClusterIP
# apply changes to redirect request 82 to container 80 ports or vice-versa.
  ports:
  - port: 82
    targetPort: 80