apiVersion: v1
kind: Service
metadata:
  name: build-app-svc
  namespace: builds
spec:
  selector:
    type: infra
    app: infra_apps
  ports:
  - nodePort: 30501 
    port: 80
    targetPort: 80
  type: NodePort
