apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        type: infra
        app: infra_apps
    spec:
      containers:
      - name: build-nginx
        image: nginx:latest
        ports:
        - container_Port: 80
        