apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
  namespace: database
  labels:
    app: db
    type: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      type: mysql
  template:
    metadata:
      labels:
        app: db
        type: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
        env:
        - name: MYSQL_USER
          value: prateek
        - name: MYSQL_PASSWORD
          value: redhat
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        volumeMounts:
        - name: databasevol
          mountPath: /var/lib/mysql/
      volumes:
      - name: databasevol
        persistentVolumeClaim: 
          claimName: mysql-data-pvc