apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-database
  namespace: database
  labels:
    app: db
    type: mysql
spec:
  selector:
    matchLabels:
      app: db
      type: mysql
  template:
    metadata:
      labels:
        app: db
        type: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: prateek
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        volumeMounts:
        - name: databasevol
          mountPath: /var/lib/mysql/
      volumes:
      - name: databasevol
        persistentVolumeClaim: 
          claimName: mysql-data-pvc