apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: database
  labels:
    app: db
    type: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /database/    # nfs server share directory
    server: 172.31.3.217  # nfs-server ip