apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxer-app
  namespace: days

spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
      os: cent
      client: cano
  template:
    metadata:
      labels:
        app: html
        os: cent
        client: cano
    spec:
      containers:
      - name: cano-oxer-app
        image: prateekkumawat/oxer:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: container-store